SymfonyCasts/EasyAdminBundle

- sfcasts/install.md
Here's my first proofread! Let me know what you think! Hopefully the formatting looks ok. I copied and pasted into a Google Doc, fixed some of the wonky formatting that happened when I pasted, then popped it back over here. It looks ok on my screen right now. I may also have neglected to capitalize certain terms appropriately. Wasn't sure if "Admin" should be capitalized or not. I also didn't know if you wanted the code you're running in the terminal to be on the same line as the rest of the text. Left it where it was for now. Hope everything sounds ok! I also re-wrote a few lines so it flowed better. Tried to imagine you speaking the lines and what might sound best.
> Proofreading the install chapter

- sfcasts/dashboard.md
Okay, there were definitely a few places here that tripped me up because I wasn't sure what was going on in the sentence without a visual reference and I could NOT get Dropbox to let me open the video files in Screenflow for some reason. (Going to restart my computer and see if that helps).
The following are key places I got lost:
-Line 9: "any new outs"? What does "outs" refer to?
-Line 29: This one confused me and I probably rephrased things slightly wrong here. Needs double checking.
-Line 37: Not sure if I phrased this line correctly either.
-Line 41: "not automatically secured" and "no security being applied" sort of sounds like the same thing, right? Also, not sure if that last sentence has the proper punctuation with ":". It sounded right when I put it there, but I'm not 100% sure. …
> Update dashboard.md - Danielle edit #1

- sfcasts/crud-controller.md
First of all, this is... a lot. I'll try to make the appropriate comments where things tripped me up. I apologize in advance for how many there will likely be.
> Update crud-controller.md - Round #1

- sfcasts/menu-items.md
Here's the first edit of menu-items. This one went much smoother because I listened to the audio and video side by side this time as opposed to just the video before. I think the biggest thing I was unsure about here was what those code snippets should look like. Let me know if there's anything I overlooked or didn't get quite right.
> Update menu-items.md - round #1

- sfcasts/assets.md
Here's my initial edit for assets.md. It went fairly smooth, but I do have a question or two which I'll post in the comments.
> Update assets.md - round #1

- sfcasts/fields.md
Just finished this edit of Fields, and I'm sure the biggest issue throughout might be proper formatting, like not knowing whether to include the "$" or "/" in a lot of places. Also, in general, I try to break up those big blocks of text into smaller, more manageable bites so it doesn't seem so overwhelming as a reader. Hope it has been ok so far.
> Update fields.md - round #1

- sfcasts/field-rendering.md
I rewrote a few sections to remove some rambling and make the objective a bit more clear. Hope it sounds okay!
> Update field-rendering.md - Round #1

- sfcasts/field-config.md
Most of the issues I had here stemmed from how all of the "fields" should appear, and what the error message should look like.
> Update field-config.md - Round #1

- sfcasts/upload.md
I wasn't sure if I needed to format `AvatarField` like this every time it appears, but I aired on the side of caution. I left the plural "fields" alone, though.
> Update upload.md - Round #1

- sfcasts/association-field.md
I re-wrote quite a bit here because there was a lot of meandering thoughts going on. This needs to be double checked for accuracy with the new wording to make sure I didn't accidentally change the meaning of something by writing it differently.
Also, when you made the "it's free" comment, I wanted to joke and be like "This feature will cost you free dollars" but I didn't think anyone would get the joke. I made myself laugh, though, so that counts for something. :D
> Update association-field.md - Round #1

- sfcasts/association-many.md
This one was... a lot. I am absolutely sure I messed up some stuff, mostly in the way i've formatted it. I'm having a hard time remembering all the rules, especially if it's something I can't visually see on the screen.
> Update association-many.md - Round #1

- sfcasts/field-configurator.md
This one was a monster. The very end of this tutorial could use a little sprucing up because it feels like it just ends abruptly. Usually there's s bit more leading up to what's next. Not sure what to say since I'm not terribly technical, though.
> Update field-configurator.md - Round #1

- sfcasts/field-template.md
I marked the moment (around 2:35 in the video/audio) where I had absolutely no idea what you were saying, so I guessed. I also don't know if I wrote the part around line 15 quite right (where you type a little, talk a little, and finish what you were typing). I know you told me how to fix that before, but I had trouble remembering what I was supposed to do. Not sure which of the past script edits that comment was on.
> Update field-template.md - Round #1

- sfcasts/custom-field.md
There was quite a bit of repetition and rambling in this one, so I tried to reword things where necessary.
> Update custom-field.md - Round #1

- sfcasts/override-template.md
I cut out a section at the end because it sounded like you changed your mind about the next step in the tutorial. Hopefully that's ok.
> Update override-template.md - Round #1

- sfcasts/permissions.md
Cut a few things out here and there if they sounded repetitive.
> Update permissions.md - Round #1

- sfcasts/entity-permissions.md
Had to break up the error message to reflect the way you were reading it. Hopefully it looks ok.
> Update entity-permissions.md - Round #1

- sfcasts/voter.md
> Update voter.md - Round #1

- sfcasts/filters.md
Reworded things a bit here and there, and there *may* be places where I forgot to add the () to the end of a method name.
> Update filters.md - Round #1

- sfcasts/events.md
Rephrased some sections slightly to make things easier to understand. Hopefully it helped.
> Update events.md - Round #1

- sfcasts/dynamic-disable-action.md
I am 100% sure I didn't format each instance of "delete action" correctly, so that definitely needs to be checked.
> Update dynamic-disable-action.md - Round #1

- sfcasts/post-action.md
This is a small quarrel, but throughout the entire tutorial, you've used "Show" and "Detail" interchangeably when the page is called "Show". I've gone along with whatever you refer to it as in the moment generally, but the more I think about it, the more I believe that could be confusing for people who read one thing and hear another. You still mouse over what you're talking about so I'm sure they can figure it out, but I thought it was worth pointing out.
> Update post-action.md - Round #1

- sfcasts/global-action.md
There's a moment where I've used the voice of the program (Ex. "Basically this says [speaking as the program]") on line 44 and I'm not sure if I formatted that quite right, using those triple ticks.
> Update global-action.md - Round #1

- sfcasts/form-panels.md
Okay, so I went on a late night Google rabbit hole looking at the difference between "collapsable" and "collapsible" and I think I ended up more confused than I started. The program that captures your words spelled it "collapsable" but EasyAdmin and I would spell it "collapsible", which made me wonder which spelling is actually appropriate/correct. (We can't change what the framework is set up to accept, of course, but it didn't stop my curiosity.) I couldn't find anything during my brief dive on the interwebs that suggests "collapsable" *isn't* a word, but also nothing really solid that says that it *is*. So it seems "collapsible", as I originally expected, is the correct and generally accepted spelling. This information impacts nothing since I'm pretty sure I caught all of the "-able" …
> Update form-panels.md - Round #1
